[project]
name = "binance-auto-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "binance-sdk-spot>=1.0.0",
    "binance-sdk-wallet>=1.0.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "pandas-ta>=0.4.71b0",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.8.0",
    "textual>=6.11.0",
    "torch>=2.9.1",
    "psutil>=6.0.0",
    "tqdm>=4.67.1",
]
